name: Enhanced_GPS
on: [push]
jobs:
  run:
    runs-on: ubuntu-latest
    container: ghcr.io/iterative/cml:0-dvc2-base1
    steps:
      - uses: actions/checkout@v3
      - uses: iterative/setup-cml@v1
      - name: ml_workflow
        run: |
          # Your ML workflow goes here
          # pip install -r requirements.txt
          # python train.py
      - name: Write CML report
        env:
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Post reports as comments in GitHub PRs
          # cat results.txt >> report.md
          # cml comment create report.md
